apiVersion: v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: holiodin/jenkins-gitops-argocd
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name:  Service Name
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer 
  ports:
  - port:  80
    targetPort:  5000
    nodePort: 32000
